name: Publish CI

on:
  push:
    tags:
      - 'dev'
      - 'release-*'

jobs:

  release:
    name: Create publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish Library
        env:
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew clean build bintrayUpload -PbintrayUser=${{ env.bintrayUser }} -PbintrayKey=${{ env.bintrayApiKey }} -PdryRun=false